### ISSUE TITLE
Failed to install in R

### ISSUE THREAD

**Issue by MFDisalreadytaken** [ilyamaclean/microclimf#1]
hi, Ilya. I tried many times, but still failed to install, even I changed the version of R. Do you know why? Thanks in advance!

**Comment by MFDisalreadytaken** [comment]
> hi, Ilya. I tried many times, but still failed to install, even I changed the version of R. Do you know why? Thanks in advance!

Sloved by using devtools.

**Comment by ilyamaclean** [comment]
I am about to push a major update to Github (microclimf is now mostly written in c++, with R wrappers - much faster and mroe memory efficient). Likely this weekend. As an interim try installing the dependent micropoint package seperately (devtools::install_github("il;yamaclean/micropoint") and then try installing microclimf (though note in the new version micropoint is not a dependent...

**Comment by ilyamaclean** [comment]
I have completed the major overhaul of the package. Give it a try now
