### ISSUE TITLE
package data sources are not available

### ISSUE THREAD

**Issue by dklinges9** [ilyamaclean/microclimf#1]
Hi Ilya,

I've been exploring the package, and attempting to run the model with the default data sources- I noticed that `dtmcaerth` and `soilc$soiltype`, both rasters, are sourced to your local drive ("C:/Fast_microclimate/data/dtm.tif "):

```
> dtmcaerth
class      : RasterLayer 
dimensions : 50, 50, 2500  (nrow, ncol, ncell)
resolution : 1, 1  (x, y)
extent     : 169475, 169525, 12475, 12525  (xmin, xmax, ymin, ymax)
crs        : +proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +units=m +no_defs 
source     : C:/Fast_microclimate/data/dtm.tif 
names      : dtm 
values     : 0.99, 16.28  (min, max)
```

As a result, I can load the objects into R, but I can't plot them or otherwise access their contents.  
I think the source for these rasters would need to be in something like `C:/soft/R/R-4.0/library/microclimf/data/dtmcaerth.tif` corresponding to the location of the R library on your drive? Because then I'd have the same filepath on my machine. So I guess installing your own package, and then manually saving the rasters to this location is what comes to mind, but not really sure how to solve. I'm just looking at [the `raster` vignette for inspiration](https://rspatial.org/raster/pkg/3-objects.html).

**Comment by dklinges9** [comment]
Hi Ilya, sorry to bother. Just letting you know that this issue is persistent, so the vignette you recently added (thanks for that) won't work until the data files are source in the remote repository. Looking forward to giving the package a test run.

**Comment by dklinges9** [comment]
Hi @ilyamaclean , thanks-- almost resolved. dtmcaerth is now available, but not soilc$soiltype, vegp$hgt, nor vegp$leafr. Could you add these too?

**Comment by ilyamaclean** [comment]
Hi Dave,

This package is beta. I'm still working on it and doing some fairly significant changes. I'll get to this, but it shouldn't be used yet

I

**Comment by ilyamaclean** [comment]
I have just completed a major update to the package and vignette and all the data sources should now be included with the package. It is now ready for testing
